server:
  port: 9020

spring:
  application:
    name: "profile"
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5832/postgres}"
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071/}"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/


info:
  app:
    name: "profiles"
    description: "Bank account ms"
    version: "1.0.0"

axon:
  axonserver:
    servers: localhost:8124
